name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ankitb2k14/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true ankitb2k14/react-test npm test
